window.__ENV__ = {
  "VITE_DEV_MODE": "false",
  "VITE_VERSION": "v4.6.0",
  "VITE_MODE": "ops",
  "VITE_BRAND": "aipub",
  "VITE_TITLE": "AI Pub",
  "VITE_BROWSER_VERSION": "latest",
  "VITE_API_URL": "https://aipub.cluster7.idc1.ten1010.io",
  "VITE_BASE_HOST": "cluster7.idc1.ten1010.io",
  "VITE_USE_MOCK": "false",
  "VITE_CLUSTER_TIMEZONE": "Asia/Seoul",
  "VITE_USE_SSO": "false",
  "VITE_LOGOUT_REDIRECT_URL": "https://aipub.cluster7.idc1.ten1010.io/welcome",
  "VITE_GRAFANA_ADMIN_URL": "https://aipub.cluster7.idc1.ten1010.io/kibana",
  "VITE_GRAFANA_USER_URL": "https://aipub.cluster7.idc1.ten1010.io/kibana",
  "VITE_KIBANA_URL": "https://aipub.cluster7.idc1.ten1010.io/kibana",
  "VITE_STREAMLIT_URL": "https://aipub.cluster7.idc1.ten1010.io/streamlit",
  "VITE_HARBOR_URL": "https://aipub-harbor.cluster7.idc1.ten1010.io",
  "VITE_NODE_URL": "https://aipub.cluster7.idc1.ten1010.io/alloc",
  "VITE_NOTICE_URL": "https://aipub.cluster7.idc1.ten1010.io/notice",
  "VITE_REPORT_URL": "https://aipub.cluster7.idc1.ten1010.io/report",
  "VITE_DOCS_URL": "https://aipub.cluster7.idc1.ten1010.io/docs",
  "VITE_SSH_PORT_MIN": "1024",
  "VITE_SSH_PORT_MAX": "65535",
  "VITE_VOLUMES": '[{"type":"nfs","value":"nfs"},{"type":"storageclass","value":"ontap-nas"}]',
  "VITE_MONITORING_API_URL": "https://aipub.cluster7.idc1.ten1010.io/monitoring-api"
};